.PHONY: install dev build preview clean run restart

install:
	@npm install

dev:
	@npm run dev

build:
	@npm run build

preview:
	@npm run preview

clean:
	@rm -rf node_modules dist

run: dev

restart: clean install dev
